### ISSUE TITLE
add glob pattern tests

### ISSUE THREAD

**Issue by jonschlinkert** [es128/path-dirname#1]
since globs are regular expressions not file paths, if we're considering using this for glob patterns we should see how this works with the following (these are just examples, there are a ton of edge cases like this):

``` js
/foo/{,/,bar/baz,qux}/
/foo[a\\\/]/
/\\*foo/
/foo\\+/
```

cc @doowb @phated

**Comment by es128** [comment]
Sure, let's do it.

Btw, just a quick heads up in case you're trying to install this that the npm registry was having problems when I published this. I have a ticket in with npm support to get it resolved.

**Comment by es128** [comment]
The thing is, though, how relevant are the results if not used in conjunction with something like is-glob?

We're adding cases like that to glob-parent, right? Would that do enough to exercise how this module interacts with them?

This one is pretty predictable in truncating after the last non-trailing slash, which might split up the glob pattern, but then you've still got glob characters in there so glob-parent will still behave appropriately afaict.

**Comment by phated** [comment]
I agree with @es128 on this. If glob-parent returns the proper result, it doesn't seem necessary to add extra logic here. Maybe we need to add these patterns to that test suite.

**Comment by es128** [comment]
Moved to https://github.com/es128/glob-parent/issues/10
